### PR TITLE
Add csrf acceptance test

### PR DESCRIPTION
**Pull request by ShaneKilkelly**

### CODE REVIEW

**Comment by jpallen** [comment]
Is this serving the same purpose as #587?

**Comment by ShaneKilkelly** [comment]
Ah, seems to be. Happy to close this one.

**Comment by jpallen** [comment]
Is this testing anything Henry's isn't? Or vice-versa? Perhaps we can combine them?

**Comment by ShaneKilkelly** [comment]
I think Henry's covers a bit more.

**Pull request closed without merging**
