### PR TITLE
Replaces '&' with '\&' when creating a project

### PR DESCRIPTION
**Pull request by rrdelaney**
When creating a project, if the user puts a '&' in the project title, the project's initial build will fail because 

``` latex
\title{This & That}
```

is not valid. 

To fix this, the title must be 

```
\title{This \& That}
```

### CODE REVIEW

**Comment by rrdelaney** [comment]
Yep, I'll implement those too

**Comment by rrdelaney** [comment]
This should be good now

**Comment by henryoswald** [comment]
Thanks, I need to check if this will effect how our drobox sync works before merging.

**Comment by henryoswald** [comment]
@jpallen I think this should actually be fine to go as is.

**Comment by rrdelaney** [comment]
Any update on this?

**Comment by jpallen** [comment]
Sorry, this got a bit overlooked. This looks like a good change. If it had a unit test, we'd be happy to merge it.

**Pull request closed without merging**
