### PR TITLE
Moved fonts to localhost for offline usage compatibility

### PR DESCRIPTION
**Pull request by mghadam**

### CODE REVIEW

**Comment by henryoswald** [comment]
Thanks, we might merge this in the near future once we get a cnd sorted for ShareLaTeX.com, at the moment I don't want to put more load on our servers.

**Comment by mghadam** [comment]
I've made it for sharelatex docker image in fact.

**Comment by henryoswald** [comment]
Thanks, Im aware of that but anything done here goes up to ShareLaTeX.com and other hosted versions as well.

**Comment by henryoswald** [comment]
I don't think we are ever going to serve these locally sorry.

**Comment by clemh78** [comment]
I have same problem. I want to host sharelatex in offline network but the fonts can not load.

Is it possible to plan this feature for docker version ?

**Pull request closed without merging**
