### PR TITLE
Remove extra security headers

### PR DESCRIPTION
**Pull request by timothee-alby**
Don't add `Strict-Transport-Security`, `X-Content-Type-Options` and `X-Frame-Options` headers.

### CODE REVIEW

**Comment by jdleesmiller** [comment]
Could you add some notes on this when ready?

Interested to know whether they caused a problem.

**Comment by jpallen** [comment]
Did some of these causes issues with web-api (it's accessed over HTTP)? Has the impact on web-api been considered?

**Comment by briangough** [comment]
The headers affect the browser, so shouldn't be a problem for internal requests.

**Comment by timothee-alby** [comment]
Follow-up here: https://github.com/overleaf/sharelatex/issues/173

I realised the issue on staging, so no impact on production

**Pull request merged**
