### PR TITLE
Un-fade editor when changing theme

### PR DESCRIPTION
**Pull request by bauerj**
Fixes sharelatex/sharelatex#232

This hides the fade for a second and then shows it again. That should be enough to see if you like the color scheme.

### CODE REVIEW

**Comment by bauerj** [comment]
@henryoswald ping

**Comment by bauerj** [comment]
:disappointed:

**Comment by henryoswald** [comment]
Sorry for being slow. This method of doing the fading isn't going to work sorry as it uses jquery to modify an angular state. As it stands it breaks the auto hide menu. Sorry!

**Comment by bauerj** [comment]
Okay, no problem.

**Pull request closed without merging**
