### PR TITLE
Load user features alongside id and email.

### PR DESCRIPTION
**Pull request by ShaneKilkelly**
Fixes a bug where project features were not applied properly,
and instead fell back to the free-account defaults.

### CODE REVIEW

**Comment by jpallen** [comment]
Can you add an acceptance test that would have caught this please (if it's reasonably straightforward)

**Comment by jpallen** [comment]
I think we also need these properties: https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Project/ProjectEditorHandler.coffee#L55

**Comment by ShaneKilkelly** [comment]
Good catch

**Comment by ShaneKilkelly** [comment]
@jpallen, added acceptance test

**Comment by jpallen** [comment]
Thanks, good spot and good fix. This could have been ugly!

**Comment by henryoswald** [comment]
we should get the acceptance tests running on the ci box.

**Pull request merged**
