### PR TITLE
Auto indent

### PR DESCRIPTION
**Pull request by manoyes**
This is the first half of a feature I requested in [Issue #152](https://github.com/sharelatex/sharelatex/issues/152). I mentioned using `latexindent.pl` to "beautify" an entire LaTeX document with a keyboard shortcut. I am still working on that feature; I could probably make a JS function for ACE ([like this](http://jsfiddle.net/HD4uj/)) rather than execute `latexindent.pl` so the code runs clientside per @henryoswald's request.

This pull request implements auto-indenting while typing using ACE's auto indent and outdent feature. It auto-indents after instances of `\begin{...}` as well as when `{`,`(`, or `[` are not closed at the end of a line, and out-outdents before instances of `\end{...}` and with single `}` on a line. Auto indentation produces the following results, without using TAB or backspace for corrections:

```
\begin{filecontents}{mybib.bib}
    @online{
        strawberryperl,
        title="Strawberry Perl",
        url="..."
    }
    @online{
        cmhblog,
        title="A Perl script for...",
        url="..."
    }
\end{filecontents}
```

```
\tikzset{
    shrink inner sep/.code={
        \pgfkeysgetvalue...
        \pgfkeysgetvalue...
    }
}
```

```
\def\Picture#1{
    \def\stripH{#1}
    \begin{pspicture}[showgrid...]
        \psforeach{\row}{
            {{3,2,1}},
            {1,2,3},
            ...
        }{
            \expandafter...
        }
    \end{pspicture}
}
```

I also updated the autocomplete snippets so they are all indented properly when spawned.

This pull request edits a part of the ACE backend. I can submit a pull request to ACE too, if it's appropriate.

### CODE REVIEW

**Comment by manoyes** [comment]
@dfelder The legal department said a committee will have to review it for public release. I wasn't given a timeline. Unfortunately it's probably low priority for them. I wish I could help expedite the changes, sorry.

**Comment by henryoswald** [comment]
Hey @manoyes, any joy with this?

**Comment by manoyes** [comment]
I don't think this is a priority for NASA. :(

The only unique code here are the regular expressions and modifying the autocomplete templates to include indentation - everything else was copied boilerplate from the ACE project on a language which used existing autoindentation capabilities within ACE. 

If you want to reengineer your own implementation of this, it shouldn't be hard - just copy how C does autoindentation in ACE and change the regular expressions for detecting the "start" and "end" of a block to work with LaTeX syntax.

**Comment by RSully** [comment]
So any updates guys?

**Pull request closed without merging**
